# -*- coding: utf-8 -*-

from . import models
from . import hr_department
from . import requisitions
from . import segments
from . import age
from . import job_tab
from . import contract_type
from . import hr_job
from . import trial_period
from . import jornada
from . import activities
from . import activities_knowledge
from . import tools_knowledge
from . import schooling
from . import language
from . import language_level
from . import competencies
from . import competencies_level
from . import competencies_type
from . import internal_relations
from . import external_relations
from . import performance_standars
from . import branchType
from . import businessType
from . import legalRepresentative
from . import stampCertificate
from . import imssRegistration
from . import city
from . import res_company
from . import jobAppAttachment
from . import clinic
from . import multiples_files
from . import vigency_complement
from . import stage_history
from . import hr_applicant
from . import res_config_settings
from . import res_users 
from . import hr_applicant_documentation
from . import hr_applicant_doc
from . import mail_mail
from . import hr_employee
from . import credentials
from . import hr_contract
from . import contract_format
from . import type_format
from . import applicant_refuse_reason
from . import product_template
from . import settings_model
from . import format_employee
from . import catalog_SAT
from . import catalog_IMSS
from . import website
# employee-services
from . import employee
from . import employee_credentials
from . import employee_todo
from . import generic_reactions
from . import reaction_mixin
from . import employee_announcement
from . import employee_request
from . import employee_request_work
from . import employee_request_loan
from . import employee_request_laborLetter
from . import employee_request_uniform
from . import employee_request_vacation
from . import employee_request_expenses
from . import employee_feedback
from . import calendar
from . import course_enrollment
from . import res_partner
from . import partner_device
from . import hr_work_location
from . import hr_attendance
# Biometric Device
from . import zk_biometric_log
from . import zk_biometric_user
from . import website_menu_fix
from . import zk_biometric_template
from . import zk_machine_attendance
from . import hoja_membretada